# Generated by Django 5.1.5 on 2025-03-31 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('LINK', 'External Link'), ('DOC', 'Document')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text="e.g., '2 hours', '4 weeks'", max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='connect_cou_categor_47a1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='connect_cou_level_d93a17_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='connect_cou_created_6173d9_idx'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.order'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='connect.product'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.order'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='connect.seller'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.course'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'created_at'], name='connect_pro_product_fa5da0_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['buyer', 'created_at'], name='connect_pro_buyer_i_319daa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'buyer', 'order')},
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['seller', 'created_at'], name='connect_sel_seller__7f206f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['buyer', 'created_at'], name='connect_sel_buyer_i_bf81bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('seller', 'buyer', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course')},
        ),
    ]
