# Generated by Django 5.1.3 on 2024-12-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_post_and_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='assigned_rider',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_fee',
        ),
    ]
