# Generated by Django 5.1.3 on 2024-12-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_remove_orderitem_assigned_rider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('bodarider', 'Boda Rider')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
