# Generated by Django 5.1.3 on 2024-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='Buyer', max_length=50),
        ),
    ]
